version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tactyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      TACTYO_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/tactyo
      TACTYO_SESSION_SECRET: dev-secret-change-me-in-production
      # IMPORTANTE: Esta é uma chave de desenvolvimento! Use scripts/generate_secrets.py para produção
      TACTYO_ENCRYPTION_KEY: 2uQEO8aR7fqVeHQUgZgPCeNj4dAgZsu_VGsSQBeQnoo=
      TACTYO_DEBUG: "true"
      TACTYO_CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    restart: unless-stopped

  # Web Frontend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
