services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tactyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: python:3.11-slim
    working_dir: /workspace/api
    command: /bin/bash -c "pip install --no-cache-dir -r requirements-dev.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --app-dir /workspace/api"
    volumes:
      - ..:/workspace:delegated
    environment:
      TACTYO_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/tactyo
      TACTYO_SESSION_SECRET: change-me-in-dev
      TACTYO_DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  web:
    image: node:20
    working_dir: /workspace/web
    command: /bin/bash -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ..:/workspace:delegated
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data:
